In [21]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [22]:
## loading the file
health_care = pd.read_csv('./healthcare/train_data.csv')

In [23]:
# Dropping these columns for now
health_care = health_care.dropna()

In [24]:
health_care.head()

,case_id,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,Stay
0,1,8,c,3,Z,3,radiotherapy,R,F,2.0,31397,7.0,Emergency,Extreme,2,51-60,4911.0,0-10
1,2,2,c,5,Z,2,radiotherapy,S,F,2.0,31397,7.0,Trauma,Extreme,2,51-60,5954.0,41-50
2,3,10,e,1,X,2,anesthesia,S,E,2.0,31397,7.0,Trauma,Extreme,2,51-60,4745.0,31-40
3,4,26,b,2,Y,2,radiotherapy,R,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,7272.0,41-50
4,5,26,b,2,Y,2,radiotherapy,S,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,5558.0,41-50

In [25]:
# Function to hot encode the column with name : name for dataframe df
def encode_text_dummy(df, name):
    dummies = pd.get_dummies(df[name])
    for x in dummies.columns:
        dummy_name = f"{name}-{x}"
        df[dummy_name] = dummies[x]
    df.drop(name, axis=1, inplace=True) ## inplace to make changed on the original df

In [26]:
## Pre processing these columns

le_string_columns = [  'Severity of Illness', 'Age' ]
dummies_string_columns = ['Hospital_type_code', 'Hospital_region_code', 'Department', 'Ward_Type', 'Ward_Facility_Code',  'Type of Admission']
encoder = LabelEncoder()
#ohEncoder = OneHotEncoder()

## label_encoded data
Xe = health_care.drop(['Stay', 'case_id'], axis=1)
Xe['Severity of Illness']= Xe['Severity of Illness'].map({'Minor': 0,  'Moderate': 1,'Extreme': 2})
Xe['Age'] = encoder.fit_transform(Xe['Age'])

ye = health_care['Stay']
ye = encoder.fit_transform(ye)
ye = 10*ye + 5
ye

for column in dummies_string_columns :
    encode_text_dummy(Xe, column)

In [27]:
## Checking Xe
Xe.head()

,Hospital_code,City_Code_Hospital,Available Extra Rooms in Hospital,Bed Grade,patientid,City_Code_Patient,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,...,Ward_Type-U,Ward_Facility_Code-A,Ward_Facility_Code-B,Ward_Facility_Code-C,Ward_Facility_Code-D,Ward_Facility_Code-E,Ward_Facility_Code-F,Type of Admission-Emergency,Type of Admission-Trauma,Type of Admission-Urgent
0,8,3,3,2.0,31397,7.0,2,2,5,4911.0,...,0,0,0,0,0,0,1,1,0,0
1,2,5,2,2.0,31397,7.0,2,2,5,5954.0,...,0,0,0,0,0,0,1,0,1,0
2,10,1,2,2.0,31397,7.0,2,2,5,4745.0,...,0,0,0,0,0,1,0,0,1,0
3,26,2,2,2.0,31397,7.0,2,2,5,7272.0,...,0,0,0,0,1,0,0,0,1,0
4,26,2,2,2.0,31397,7.0,2,2,5,5558.0,...,0,0,0,0,1,0,0,0,1,0

In [28]:
## getting the inputs and labels
X = Xe.values
y = ye

print('X.shape', X.shape)
print('y.shape', y.shape)

X.shape (313793, 40)
y.shape (313793,)

In [29]:
# Mean of Stay
print(f'The mean of stay is {ye.mean()} days')

The mean of stay is 31.960034162648626 days

# Linear Regression

In [36]:
from sklearn.linear_model import LinearRegression
from sklearn import metrics

model = LinearRegression(fit_intercept=True)
model.fit(X, y)
a, b, score = model.coef_, model.intercept_, model.score(X, y)

# Predict
pred = model.predict(X)

c = np.sqrt(metrics.mean_squared_error(pred,y))

print('score : %.2f' % score)
print('RMSE : %.2f' % c)

score : 0.39
RMSE : 16.81

# Lasso Regression

In [31]:
import sklearn
from sklearn.linear_model import Lasso


# Create linear regression
regressor = Lasso(alpha=0.01)

# Fit/train LASSO
regressor.fit(X,y)
# Predict
pred = regressor.predict(X)

a= regressor.coef_
b = regressor.intercept_
c = np.sqrt(metrics.mean_squared_error(pred,y))

print('RMSE : %.2f' % c)
print('score : %.2f' % regressor.score(X,y))

RMSE : 16.81
score : 0.39

In [34]:
# alpha = 0.1


# Create linear regression
regressor = Lasso(alpha=0.1)

# Fit/train LASSO
regressor.fit(X,y)
# Predict
pred = regressor.predict(X)

a= regressor.coef_
b = regressor.intercept_
c = np.sqrt(metrics.mean_squared_error(pred,y))

print('RMSE : %.2f' % c)
print('score : %.2f' % regressor.score(X,y))

RMSE : 16.88
score : 0.38

In [35]:
# alpha = 1


# Create linear regression
regressor = Lasso(alpha=0.1)

# Fit/train LASSO
regressor.fit(X,y)
# Predict
pred = regressor.predict(X)

a= regressor.coef_
b = regressor.intercept_
c = np.sqrt(metrics.mean_squared_error(pred,y))

print('RMSE : %.2f' % c)
print('score : %.2f' % regressor.score(X,y))

RMSE : 16.88
score : 0.38