In [2]:
import os
# import sys
import pandas as pd
import numpy as np
# import sklearn as sk
# import tensorflow as tf
# import matplotlib.pyplot as plt
# from tensorflow import keras

In [3]:
path = "healthcare"

filename_read = os.path.join(path, "train_data.csv")
df = pd.read_csv(filename_read, na_values=['NA', '?'])

# print(df[0:5])
print(df.shape)
print(df.columns)

(318438, 18)
Index(['case_id', 'Hospital_code', 'Hospital_type_code', 'City_Code_Hospital',
       'Hospital_region_code', 'Available Extra Rooms in Hospital',
       'Department', 'Ward_Type', 'Ward_Facility_Code', 'Bed Grade',
       'patientid', 'City_Code_Patient', 'Type of Admission',
       'Severity of Illness', 'Visitors with Patient', 'Age',
       'Admission_Deposit', 'Stay'],
      dtype='object')

In [4]:
df.drop(df.columns[0:5],axis=1, inplace=True)
df

,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,Stay
0,3,radiotherapy,R,F,2.0,31397,7.0,Emergency,Extreme,2,51-60,4911.0,0-10
1,2,radiotherapy,S,F,2.0,31397,7.0,Trauma,Extreme,2,51-60,5954.0,41-50
2,2,anesthesia,S,E,2.0,31397,7.0,Trauma,Extreme,2,51-60,4745.0,31-40
3,2,radiotherapy,R,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,7272.0,41-50
4,2,radiotherapy,S,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,5558.0,41-50
...,...,...,...,...,...,...,...,...,...,...,...,...,...
318433,3,radiotherapy,Q,F,4.0,86499,23.0,Emergency,Moderate,3,41-50,4144.0,11-20
318434,2,anesthesia,Q,E,4.0,325,8.0,Urgent,Moderate,4,81-90,6699.0,31-40
318435,3,gynecology,R,F,4.0,125235,10.0,Emergency,Minor,3,71-80,4235.0,11-20
318436,3,anesthesia,Q,D,3.0,91081,8.0,Trauma,Minor,5,11-20,3761.0,11-20
318437,5,gynecology,Q,C,2.0,21641,8.0,Emergency,Minor,2,11-20,4752.0,0-10

In [5]:
df.drop(df.columns[2:7], axis=1, inplace=True)
df

,Available Extra Rooms in Hospital,Department,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,Stay
0,3,radiotherapy,Emergency,Extreme,2,51-60,4911.0,0-10
1,2,radiotherapy,Trauma,Extreme,2,51-60,5954.0,41-50
2,2,anesthesia,Trauma,Extreme,2,51-60,4745.0,31-40
3,2,radiotherapy,Trauma,Extreme,2,51-60,7272.0,41-50
4,2,radiotherapy,Trauma,Extreme,2,51-60,5558.0,41-50
...,...,...,...,...,...,...,...,...
318433,3,radiotherapy,Emergency,Moderate,3,41-50,4144.0,11-20
318434,2,anesthesia,Urgent,Moderate,4,81-90,6699.0,31-40
318435,3,gynecology,Emergency,Minor,3,71-80,4235.0,11-20
318436,3,anesthesia,Trauma,Minor,5,11-20,3761.0,11-20
318437,5,gynecology,Emergency,Minor,2,11-20,4752.0,0-10

In [6]:
# df.drop([4,6])
# print(df.columns)

In [7]:
#manipulations on a copy to have an original for further manipulation
new_df = df.copy()
new_df = new_df.select_dtypes(include=["int","float"])

headers = list(new_df.columns.values)

In [8]:
fields = []

In [9]:
for field in headers:
    fields.append({
        "name":field,
        "mean":df[field].mean(),
        "var":df[field].var(),
        "sdev":df[field].std()
    })

In [10]:
for field in fields:
    print(field)

{'name': 'Available Extra Rooms in Hospital', 'mean': 3.1976271676119055, 'var': 1.364624484865746, 'sdev': 1.1681714278588335}
{'name': 'Visitors with Patient', 'mean': 3.2840992595104854, 'var': 3.1119125861261314, 'sdev': 1.7640613895571013}
{'name': 'Admission_Deposit', 'mean': 4880.749392346391, 'var': 1181082.625479292, 'sdev': 1086.7762536416094}

In [11]:
#shuffling
df= df.reindex(np.random.permutation(df.index))
df.reset_index(inplace=True, drop=True)

In [12]:
df

,Available Extra Rooms in Hospital,Department,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,Stay
0,2,gynecology,Trauma,Extreme,2,51-60,5972.0,21-30
1,2,gynecology,Emergency,Extreme,2,41-50,6150.0,31-40
2,3,gynecology,Trauma,Minor,3,61-70,6725.0,11-20
3,4,radiotherapy,Emergency,Minor,2,81-90,5265.0,11-20
4,2,gynecology,Emergency,Moderate,5,41-50,3715.0,11-20
...,...,...,...,...,...,...,...,...
318433,3,gynecology,Urgent,Minor,2,21-30,5775.0,11-20
318434,1,anesthesia,Emergency,Extreme,2,61-70,3832.0,0-10
318435,2,anesthesia,Emergency,Moderate,4,61-70,5241.0,31-40
318436,2,radiotherapy,Trauma,Moderate,2,41-50,4772.0,11-20
318437,6,radiotherapy,Trauma,Minor,3,41-50,4539.0,11-20

In [13]:
#missing values
df.isnull().values.any()

False