In [10]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [4]:
## loading the file
health_care = pd.read_csv('./healthcare/train_data.csv')

In [8]:
health_care.tail()

,case_id,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,Stay
318433,318434,6,a,6,X,3,radiotherapy,Q,F,4.0,86499,23.0,Emergency,Moderate,3,41-50,4144.0,11-20
318434,318435,24,a,1,X,2,anesthesia,Q,E,4.0,325,8.0,Urgent,Moderate,4,81-90,6699.0,31-40
318435,318436,7,a,4,X,3,gynecology,R,F,4.0,125235,10.0,Emergency,Minor,3,71-80,4235.0,11-20
318436,318437,11,b,2,Y,3,anesthesia,Q,D,3.0,91081,8.0,Trauma,Minor,5,11-20,3761.0,11-20
318437,318438,19,a,7,Y,5,gynecology,Q,C,2.0,21641,8.0,Emergency,Minor,2,11-20,4752.0,0-10

The columns to be pre-processed are :
1. Hospital_type_code
2. Hospital_region_code
3. Department
4. Ward_type
5. Ward_Facility_Code
6. City_Code_Patient
7. Type of Admission
8. Severity of Illness
9. Age
10. Admission_Deposit
11. Stay

In [9]:
health_care.columns

Index(['case_id', 'Hospital_code', 'Hospital_type_code', 'City_Code_Hospital',
       'Hospital_region_code', 'Available Extra Rooms in Hospital',
       'Department', 'Ward_Type', 'Ward_Facility_Code', 'Bed Grade',
       'patientid', 'City_Code_Patient', 'Type of Admission',
       'Severity of Illness', 'Visitors with Patient', 'Age',
       'Admission_Deposit', 'Stay'],
      dtype='object')

In [11]:
## Pre processing these columns

string_columns = ['Hospital_type_code', 'Hospital_region_code', 'Department', 'Ward_Type', 'Ward_Facility_Code', 'City_Code_Patient', 'Type of Admission', 'Severity of Illness', 'Age', 'Admission_Deposit', 'Stay' ]
encoder = LabelEncoder()

for column in string_columns :
    health_care[column] = encoder.fit(health_care[column]).transform(health_care[column])
    
health_care.head()

,case_id,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,Stay
0,1,8,2,3,2,3,3,2,5,2.0,31397,6,0,0,2,5,2954,0
1,2,2,2,5,2,2,3,3,5,2.0,31397,6,1,0,2,5,3997,4
2,3,10,4,1,0,2,1,3,4,2.0,31397,6,1,0,2,5,2788,3
3,4,26,1,2,1,2,3,2,3,2.0,31397,6,1,0,2,5,5315,4
4,5,26,1,2,1,2,3,3,3,2.0,31397,6,1,0,2,5,3601,4

In [12]:
## getting the inputs and labels

X = health_care.drop(['Stay', 'case_id', 'patientid'], axis=1)
y = health_care['Stay'].values

In [13]:
print('X.shape', X.shape)
print('y.shape', y.shape)

X.shape (318438, 15)
y.shape (318438,)